tasks:
  - init: cd install && bash install.sh
  - command: APACHE_DOCROOT_IN_REPO=moodle-master && apache2ctl start
image:
  file: .gitpod.Dockerfile
ports:
  - port: 8001
    onOpen: open-preview
vscode:
  extensions:
    - esbenp.prettier-vscode@2.3.0:1F0Pvb/ORZ/T+b60LIMs8w==
